apiVersion: v1
kind: Service
metadata:
  name: prometheus-test-service
  labels:
    app: prometheus-test-app
spec:
  selector:
    app: prometheus-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
