apiVersion: v1
kind: Service
metadata:
  name: prometheus-test-service
  namespace: prometheus-test
  labels:
    app: prometheus-test-app
spec:
  type: LoadBalancer
  selector:
    app: prometheus-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-test-app
  namespace: prometheus-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus-test-app
  template:
    metadata:
      labels:
        app: prometheus-test-app
    spec:
      containers:
      - name: test-pod
        image: 234401896482.dkr.ecr.us-west-2.amazonaws.com/prometheus_test_pod:latest
        ports:
        - name: http
          containerPort: 5000
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 100M
          limits:
            cpu: 2000m
            memory: 1G
      nodeSelector:
        kubernetes.io/os: linux
---
